name             'chef-mailcatcher'
maintainer       'SPINEN'
maintainer_email 'keli.grubb@spinen.com'
license          'Apache License v2.0'
description      'Installs/Configures mailcatcher'
long_description 'Installs/Configures mailcatcher'
version          '0.2'

recipe 'chef-mailcatcher', 'Installs a single configurable instance of mailcatcher and installs/configures postfix.'

supports 'rhel'
supports 'centos'
supports 'suse'
supports 'ubuntu'
supports 'debian'